### ISSUE TITLE
What is the architecture of this project and how can I help? + other questions

### ISSUE THREAD

**Issue by PostsDesert** [CSDSpartans/attendance#1]
So from what I gathered this program generates a QR code that we put in rooms and then scan through a website (with maybe future integration with an app). The front end appears to be using javascript and the backend will be managed using python (hopefully using flask). Did I get anything off / anything else. 
Also what would be the best way to contribute to this? I have experience with React Native (iOS / android app), Swift (iOS), and Python.

**Comment by colevahey** [comment]
Yes alright, sorry I was out of town for a few days... You have grasped the general concept, however, the thought was that the students would be the ones with the QR/barcodes (which I'll get to in a second) and there will be scanners in the classrooms. Originally, we were going to use QR codes, but I found a VERY cool trinket [here](https://www.adafruit.com/product/1203?gclid=CjwKEAjwsqjKBRDtwOSjs6GTgmASJACRbI3ftCUzYGDZlFPTT5eBjCxmbIMBIUyW4kTYfzPl8hezqhoCI3vw_wcB) which I think would be awesome to work with, and we could design the casing  as well as the functionality with the website etc. As for your contribution, I remember you telling me about a way you were communicating with schoology which I will definitely need help with... Also, the app in the future will be great for the teachers to use depending on where this project goes.

**Comment by PostsDesert** [comment]
Okay That would work too. The link is a camera based scanner, which would work with QR codes too.

**Comment by colevahey** [comment]
I think with this one, it has the reader included as well which is designed for barcodes specifically... It really doesn't matter because with code 128 barcodes, you can encode most words and symbols.

**Comment by PostsDesert** [comment]
Heres some pros to QR Codes I pulled off a website for curiosity. 
> A conventional barcode can take up to ten times the amount of printing space as a QR code carrying the same amount of information. 

> A QR code is capable of being read in 360 degrees, from any direction, thus eliminating any interference and negative effects from backgrounds.

>Also, the algorithm which is used to create QR codes will allow for an error margin (approx. 7-30%). “So what?” you ask? Well, this doesn’t just help with scanning purposes in case the item or code in question is dirty or damaged. Knowing this feature, you can alter the QR code symbol to include a logo, keyword, picture, etc.

**Comment by colevahey** [comment]
PS just added the local barcode generation.
