### ISSUE TITLE
The use of RFID / Magnetic Tags

### ISSUE THREAD

**Issue by PostsDesert** [CSDSpartans/attendance#2]
*The main downside with QR codes are that a user can take a picture and scan without physically being in the room.* I'm assuming that we are using the QR codes for and only for people that own smartphones and a website login as a fallback.
An alternative that we could look into is Bluetooth Low energy Beacons. This would allow passive clock in, without the user having to scan a code. It would also benefit for being harder to replicate and fake a login.
    The beacons work with iOS 7.0+ and Android 4.2+, and also work with macOS and possibly chromeOS if it supports bluetooth 4.0+ (although tying a user id to a Chromebook Mac would be another issue).

Some links:
Company that sells attendance tech ready made:
https://9to5mac.com/2014/03/28/behere-app-uses-ibeacons-to-automatically-take-attendance-as-students-enter-the-classroom/

Companies that has deployed the technology and had success:
http://www.inntot.com/casestudies_iot_ble_eas.html
http://proximitystudio.com/employee-attendance-tracking-gets-iot-treatment/

Making the Bluetooth Low Energy Beacon:
http://makernews.info/featured/2015/09/BLE-nrf24l01-arduino.html
http://beekn.net/guide-to-ibeacons/

    Price / Fallback support seems to be the main issues with this approach. It's pretty cool through as the Bluetooth Low energy beacons have a lot more potential than attendance. Fallback support is going to be a problem that will need to be faced regardless and will need to be handled in a manner that users don't only use the fallback approach.

   If you want to talk to Joe and maybe pursue this farther I can do some more price digging.

**Comment by PostsDesert** [comment]
Another thought I just had is using the wifi router to detect the users based on distance. I have no idea if out router has the software configured to do this and it seems less practical than BLE beacons or QR Codes but it's another option. 

Link:
http://www.libelium.com/products/meshlium/smartphone-detection/

**Comment by PostsDesert** [comment]
If we do go the QR Code route, we should probably swap to a python library to generate the code so we have less of a dependency on outside servers.

**Comment by colevahey** [comment]
If you look at my comment on issue 1, I talk about the fact that rather than the kids having the scanners, the classrooms will... Looking at your close range bluetooth sensors made me think of RFID/NFC sensors, sorta like hotel keycards, which would also be really cool, and not as easy to be duplicated. Found [this](https://www.adafruit.com/product/789) for the RFID and arduino which would be awesome... I don't know as much about production of the actual cards here, but I will look into it. Security will be a challenging part of this project.

**Comment by colevahey** [comment]
Here are some [NFC Cards](http://www.id-enhancements.com/nfc-pvc-card-ntag216/?gclid=CjwKCAjwzMbLBRBzEiwAfFz4gVr-pmBtHmFlNjCiHOkDz3nZ0HxmgcJrl9vm3Cf9GtoO9Je_XBh4zxoC1-UQAvD_BwE) which we could write to.

**Comment by PostsDesert** [comment]
I wish NFC Card would work since their so cheap. But [Apple only started supporting them with iOS 11 and iPhone 7 / 7+](https://developer.apple.com/documentation/corenfc).

**Comment by PostsDesert** [comment]
Ohh you meant where we give every student a card. That would work. My dad uses that for his shop but it's a magnetic system not RFID. [RFID has been done before](http://www.rfidjournal.com/articles/view?1408). Why did admin want this since our school is so small? This may be overkill too and the QR code / barcode a more practical route. [Here's someone that asked the question on quora.](https://www.quora.com/How-do-I-setup-a-cheap-RFID-system-for-attendance-or-any-other-purpose)

**Comment by colevahey** [comment]
I think Joe just came up with the idea for attendance, but with RFID or magnetic we could make the school more secure all the way out to the perimeter doors (not that we need it). The advantage of barcodes would be rather than $1.20 NFC cards, we could print stickers for dirt cheap for students.

**Comment by PostsDesert** [comment]
Yeah barcodes sounds good. Have we tested one of the scanners yet? Because if its not fast we're going to have problems.

**Comment by colevahey** [comment]
Yeah I know... This project is kinda delayed until school starts when we can really get in and test, not only with the hardware, but also with software communications with schoology etc.

**Comment by PostsDesert** [comment]
Ohh I see to log attendance in Schoology. Idk where I thought it was going to be logged. Cant they create a test class with an admin account, so we could start working on the Schoology integration?

**Comment by PostsDesert** [comment]
Because we would use the reader to scan the data to json or python dict and then send it to schoology, right? It would be nice to be able to start on the second part and feed dummy json data. What data is the QR code / barcode going to contain? Name and student id?

**Comment by colevahey** [comment]
Exactly... I'm going to wait until the school year to ask for that sort of "test class". Definitely will use json to log present vs absent into schoology. As for the information contained in the qr code/barcode, I wasn't sure... I think ID may be overkill if we aren't going to use it for anything, and at this time I can't think of a use for it.
